// Add here the contents of the Diaporama, music and images
// TODO doc

let content = [
	{end: 13},
	{img: "sample/horizontal.jpg", text: "horizontal"},
	{img: "sample/vertical.jpg", text: "vertical"},
	{img: "sample/free-photo-of-nature-clairiere-desert-campagne.jpeg", text: "diaporama"},
	{img: "sample/pexels-photo-5646986.webp", params: "left", text: "on the left side"},
	{img: "sample/pexels-photo-4946623.jpeg", params: "right", text: "on the right side"},
	{music: "sample/Pixabay - Lexin Music - science-documentary-169621.mp3", end: 16},
	{img: "sample/free-photo-of-oiseau-eau-lac-riviere.jpeg", text: "synchronised with music"},
	{img: "sample/pexels-photo-9107941.jpeg", params: "small left", text: "with a long comment below, just to see how it's displayed, the text should not overflow"},
	{img: "sample/pexels-photo-428062.webp", params: "right big", text: "big"},
	{music: "sample/enigma-dream-Pixabay - Top FLow Production - 170618.mp3", begin: 50, end: 80},
	{img: "sample/free-photo-of-maisons-batiments-construction-arbres.jpeg", text: "new music track"},
	{img: "sample/free-photo-of-ville-eau-rue-building.jpeg", params: "left top small"},
	{img: "sample/pexels-photo-592636.jpeg", params: "left bottom small"},
	{img: "sample/pexels-photo-13012336.jpeg", params: "right top small"},
	{img: "sample/pexels-photo-19321364.webp", params: "right bottom small"},
	{img: "sample/pexels-photo-19328977.webp", params: "small"},
	{music: "sample/Pixabay - Lexin Music - eco-technology-145636.mp3", begin: 10, end: 38},
	{img: "sample/free-photo-of-ville-bleu-construction-motif.jpeg", params: "left ", defaultDelay: 0.5, defaultDuration: 0.1, text: "fast"},
	{img: "sample/pexels-photo-10802099.jpeg", params: "right"},
	{img: "sample/pexels-photo-8640342.jpeg", params: "left"},
	{img: "sample/pexels-photo-18952277.webp", params: "center"},
	{img: "sample/pexels-photo-12532586.jpeg", params: "right"},
	{img: "sample/free-photo-of-bois-route-paysage-nature.jpeg", params: "center"},
	{img: "sample/free-photo-of-bois-lumineux-ville-rue.jpeg", params: "left"},
	{img: "sample/free-photo-of-aube-paysage-soleil-couchant-sable.jpeg", params: "right", defaultDelay: null, defaultDuration: null, text: "slow again"},
	{img: "sample/pexels-photo-14426570.jpeg", params: "smaller left", delay: 4, duration: 2, text: "smaller and very slow"},
	{img: "sample/free-photo-of-monument-voyager-pierre-histoire.jpeg", params: "right"},
	{img: "sample/pexels-photo-19070935.webp", params: "left"},
	{img: "sample/free-photo-of-mer-soleil-couchant-plage-sable.jpeg", text: "the end"},
];
